server:
  port: 8769    #default port where the service will be started
  context-path: /pioneer-authorization-server
  use-forward-headers: false
 
eureka:         #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    hostname: localhost
    port: 8761
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
 
spring:    
  application:
    name: pioneer-authorization-server   #current service name to be used by the eureka server
     
#management:
#  security:
#    enabled: true  #disable the spring security on the management endpoints like /env, /refresh etc.
 
 
security:
  basic:
    enabled: false
  user:
    password: password
  ignored: /css/**,/js/**,/favicon.ico,/webjars/** 

logging:
  level:
    org.springframework.security: DEBUG    