server:
  port: 8769    #default port where the service will be started
 
eureka:         #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
 
spring:    
  application:
    name: pioneer-authorization-server   #current service name to be used by the eureka server
     
management:
  security:
    enabled: true  #disable the spring security on the management endpoints like /env, /refresh etc.
 

logging:
  level:
    org.springframework.security: DEBUG    