server:
  port: 5000

security:
  jwt:
    key-store: classpath:keystore.jks
    key-store-password: letmein
    key-pair-alias: mytestkey
    key-pair-password: changeme

eureka:         #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://eurekaserver.us-east-2.elasticbeanstalk.com/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  application:
    name: pioneer-authentication-server      